#! /bin/bash

if [ $# != 2 ] ; then
echo "Usage:compileModule moduleFile [kernel-version]"
echo "Example:compileModule kmod.c 4.4.72"
exit 1;
fi

cp ~/kernelAll/Makefile ./

file=$1
file=${file//.c/.o}
version=$2

sed -i '/obj-m := /d' ./Makefile
sed -i '/KERNELDR := /d' ./Makefile

sed -i "/PWD := /iobj-m := ${file}" ./Makefile
sed -i "/PWD := /iKERNELDR := ~/kernelAll/kernelSource/linux-${version}" ./Makefile
make
rm ./Module.symvers ./modules.order ./*.o ./*.mod.c

file=${file//.o/.ko}
cp $file ~/kernelAll/rootfs/tmp/
cd ~/kernelAll

sed -i "/insmod/d" init
sed -i "/#loadKo/ainsmod /tmp/${file}" init
cp init ~/kernelAll/rootfs/
cd ~/kernelAll/rootfs
gen_rootfs rootfs
cp ~/kernelAll/rootfs.cpio ~/kernelAll/kernelPwn/kernel-${version}/